### ISSUE TITLE
Incorrect default guidance & guidance selections

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmp#78]
I tested various combinations of creating a plan and always get the wrong default template (DMP Template from DCC - screenshot below). In addition, I get a weird assortment of guidance options with the wrong default guidance (Digital Curation Centre - screenshot below) and the default guidance is not selected.

Correct default template is called "Digital Curation Centre" (the wrong templates are displayed in the public Funder Requirements list too). Correct default guidance is called "DMPTool." Desired behavior is to provide the correct template and correct guidance auto-selected. The guidance list should have the following options only (auto-selected):
- DMPTool
- University of California Office of the President (UCOP)

![screen shot 2018-02-19 at 11 37 33 am](https://user-images.githubusercontent.com/12703638/36394620-feb773e0-1569-11e8-81f8-8143a1f69273.png)

**Comment by briri** [comment]
I just synced up the dmptool-stg database with what you have in dmp2-stg (where we fixed the default template issue). Please give it another try

**Comment by stephaniesimms** [comment]
@briri - thanks, now I get the correct default template when I create a plan and in the Funder Requirements page. template issue is resolved.

I still don't get the correct default guidance, however. and still have the weird assortment of options in the screenshot above.

**Comment by briri** [comment]
auto select default org's guidance, and selected research org's guidance

only show default org's guidance, and selected research org's guidance and my org's guidance on priority section

**Comment by stephaniesimms** [comment]
the problem with the weird selections is that they aren't actually Guidance created by an Org. the selections coming up in the DMPTool are Funder/Org guidance attached to the Funder/Org templates. so the content is really long and not appropriate as guidance for other templates. the desired/correct behavior is not to include DOT, USGS, NOAA, WHOI in guidance selections at all.

**Comment by stephaniesimms** [comment]
it sounds like this can be resolved by the steps we discussed: 1) delete guidance groups for these funder/orgs. this guidance should be attached to templates as annotations and was mistakenly migrated as guidance. 2) make DMPTool/UCOP guidance the default. DCC guidance should be a duplicate but i need to verify. i know DMPTool guidance is correct and that's the label we want to use.

**Comment by stephaniesimms** [comment]
after latest testing on dmptool-stg, the weird Org options are cleared up. The default guidance behavior is still strange (screenshot below). 

I see two options: UCOP and DMPTool and UCOP is checked. Ideally there should just be one called DMPTool that is checked. When I go to write the plan, I get the "DCC" guidance instead of DMPTool. If necessary you can replace the DCC guidance group with the DMPTool guidance group if that alleviates the default guidance issues. Or make UCOP/DMPTool the default.


![screen shot 2018-02-25 at 3 54 46 pm](https://user-images.githubusercontent.com/12703638/36648147-46c269e0-1a44-11e8-9e29-acc2d23a9e4d.png)

**Comment by briri** [comment]
what server were you on when you tested this? I believe I only made my changes on stage.

**Comment by stephaniesimms** [comment]
i'm testing on stage. and it did this during the webinar just now.

**Comment by stephaniesimms** [comment]
hallelujah it's working as expected now. Org short names appear in tabs and everything. UCAR template and guidance data are also fixed. closing issue!
